language: node_js
node_js:
- node
deploy:
  provider: heroku
  app: weather-forecast-redux
  skip_cleanup: true
  api_key:
    secure: tbG8xL9xKv26HlM31t57lS56kW2dHQmJvWbEJ4d13B26cFQ1FYVLDHAbd63a5jbA4IhWizmoGCDY9WdKabU1B863iwm03zJteNG4PXz1+b23vVFEG+apvEGQkeSlULCeh6wWwms6yavEQDMfYodW1fABQ2g0keax7uwOuguCuR6J9w6McqiReDIPJTEPzCi2GPh/bWBZu+paHmSMaBJ1jrszSyGmW5vVjq1533Tvtiu5OpOSgmkq2v2TrI6bRtFgSVLqG3BUpabT4p0z2dOVTyivFDyIF61gDPbLplryl64uRHPPTFAxWLDHX1EXOr+XLLFuReyjlN7Ffv7f/2IWDVikzD1ATfCcl6f0nIhfi7Y+AEz9UeU8eSl0DOQo87GF3mXX3YSXE2tOIO1uwLT25AHu7zhrFHQYaQW/gzeH4B77Og1tmF1S9NbLiFioRyP6eNYz8aDL8MY3jnHAmKouemKeL9nLa5H1iduR3eXQJJUMpJuY/B1lM1f8Dkd1PuY2m5TZxbqYPzYCx6CyipGdrC15Xsyfd8R2IoN4rCX9a5OqQoLNxiHGTTS+df5Ms34IZ2OMODTs3Fnh41UURspRRN81zBsSgH3K33MmhQxajP3GSE+DSzGTM28ryWfHKZCgKxeR1TQ+OePqNILGRo5z6BEkqMotOAF10AQ7Xw/FQM8=